#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>

#include "../graph.h"
#include "../loading.h"


/**
 * Print --help message
 */
void printHelp() {
	printf("Maps a output file of sts or tpk to the expected input of gaston graph mining\n");
	printf("Either give filename as an argument or pipe something in\n");
}


void mapGraph2Gaston(FILE* data, struct GraphPool* gp, struct ShallowGraphPool* sgp) {
	int bufferSize = 100;
	int graphNumber;
	struct ShallowGraph* patterns;
	char** labels = aids99VertexLabelArray();

	/* try to load a file */
	createFileIterator(argv[1], gp);


	/* iterate over all graphs in the database */
	while (((i < maxGraphs) || (maxGraphs == -1)) && (g = iterateFile(&aids99VertexLabel, &aids99EdgeLabel))) {

		/* if there was an error reading some graph the returned n will be -1 */
		if (g->n > 0) {
			int v;

			fprintf(stdout, "t # %i\n", g->number);


			/* print vertices */
			for (v=0; v<g->n; ++v) {
				int i;
				for (i=0; i<64; ++i) {
					if (strcmp(g->vertices[v]->label, labels[i]) == 0) {
						fprintf(stdout, "v %i %i\n", v + offset, i);
						break; /* continue with next vertex */
					}
				}
			}
			
			/* print edges */
			for (v=0; v<g->n; ++v) {
				struct VertexList* e;
				for (e=g->vertices[v]->neighborhood; e!=NULL; e=e->next) {
					if (e->endPoint->number > v) {
						fprintf(stdout, "e %i %i %s\n", v + offset, e->endPoint->number + offset, e->label);
					}
				}
			}

			++i;

			/* garbage collection */
			dumpGraph(gp, g);

		} else {
			/* TODO should be handled by dumpgraph */
			free(g);
		}
	}
	free(labels);
}


/**
 Main method of the TreePatternKernel levelwise pattern generation algorithm.
 It will use a database of spanning trees generated by the preprocessing 
 algorithm accompanying it.
 */
int main(int argc, char** argv) {
	if ((argc > 2) || (strcmp(argv[1], "--help") == 0) || (strcmp(argv[1], "-h") == 0)) {
		printHelp();
		return EXIT_FAILURE;
	} else {

		/* create object pools */
		struct ListPool *lp = createListPool(1);
		struct VertexPool *vp = createVertexPool(1);
		struct ShallowGraphPool *sgp = createShallowGraphPool(1, lp);
		struct GraphPool *gp = createGraphPool(1, vp, lp);

		FILE* data;

		if (argc == 1) {
			mapGraph2Gaston(stdin, gp, sgp);
		} else {
			data = fopen(argv[1], "r");
			if (data == NULL) {
				fprintf(stderr, "Could not open file provided by argument.\n");
				return EXIT_FAILURE;
			}
			mapGraph2Gaston(data, gp, sgp);
			fclose(data);
		}
		
		/* garbage collection */
		freeGraphPool(gp);
		freeShallowGraphPool(sgp);
		freeListPool(lp);
		freeVertexPool(vp);

		return EXIT_SUCCESS;
	}
}
